nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']
        allow_methods: ['GET', 'PUT', 'POST', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        allow_credentials: true

    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173']
            allow_methods: ['GET', 'PUT', 'POST', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            allow_credentials: true
